intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += fmt%lib{fmt}
import intf_libs += range-v3%lib{range-v3}

import impl_libs += ctre%lib{ctre}

lib{gerbil}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBGERBIL_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBGERBIL_SHARED_BUILD

# Export options.
#
lib{gerbil}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{gerbil}: cxx.export.poptions += -DLIBGERBIL_STATIC
libs{gerbil}: cxx.export.poptions += -DLIBGERBIL_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{gerbil}: bin.lib.version = "-$version.project_id"
else
  lib{gerbil}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libgerbil/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libgerbil/
  install.subdirs = true
}
