libs =
import libs += libcacao%lib{cacao}
import libs += libmannele%lib{mannele}
import libs += libutils%lib{utils}
import libs += entt%lib{entt}
import libs += stb_image_write%lib{stb_image_write}
import libs += tinyobjloader%lib{tinyobjloader}

exe{sph-simulation}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.poptions += -DVULKAN_HPP_NO_STRUCT_CONSTRUCTORS
