./: file{** -buildfile}

# Compile all vertex shaders
#
file{~'/(.+)\.vert\.spv/'}: file{~'/\1\.vert/'}
{{
    diag glslc ($<[0])

    glslc -o $path($>[0]) $path($<[0])
}} 

# Find all compiled shader files and set them up for installation.
# 
file{~'/.*\.spv/'}:
{
    install = "$install.share/assets/shaders/"
    install.subdirs = true
}
