intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libreglisse%lib{reglisse}
import intf_libs += range-v3%lib{range-v3}
import intf_libs += asserts%lib{asserts}
import intf_libs += magic_enum%lib{magic_enum}

lib{mannele}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

if $enable_debug_logging
    cxx.poptions += -DLIBMANNELE_ENABLE_DEBUG_LOGGING

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBMANNELE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBMANNELE_SHARED_BUILD

# Export options.
#
lib{mannele}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{mannele}: cxx.export.poptions += -DLIBMANNELE_STATIC
libs{mannele}: cxx.export.poptions += -DLIBMANNELE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{mannele}: bin.lib.version = @"-$version.project_id"
else
  lib{mannele}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the libmannele/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libmannele/
  install.subdirs = true
}
