name: Documentation

on:
  push:
    branches: [ water_sim ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install build2:
        run: |
          ls -lah
          mkdir build2-build && cd build2-build
          curl -sSfO https://download.build2.org/0.13.0/build2-install-0.13.0.sh
          shasum -a 256 -b build2-install-0.13.0.sh
          sh build2-install-0.13.0.sh
