name: Documentation

on:
  push:
    branches:
      - 'docs-ci'

jobs:
  build:
    name: Build & Public Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get remove llvm-11 llvm-10 gcc-9
          sudo apt-get remove clang-11 clang-10
          sudo apt-get -y update
          sudo apt-get -y install wget gnupg curl
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo bash -c "echo \"deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main\" >> /etc/apt/sources.list.d/llvm.list"
          sudo bash -c "echo \"deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main\" >> /etc/apt/sources.list.d/llvm.list"
          sudo apt-get -y update
          sudo apt-get -y install \
            libtbb-dev \
            build-essential \
            meson \
            ninja-build \
            cmake \
            xxd \
            clang-12 \
            libclang-common-12-dev \
            libclang-12-dev \
            lld-12 \
            groff \
            unzip \
            pkg-config \
            git \
            zlib1g-dev \
            libssl-dev \
            libcurl4-openssl-dev
          sudo apt install build-essential manpages-dev software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-9 \
            --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 \
            --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-11 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-11 \
            --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 \
            --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11

          #   - name: Get Compilation Database
          #     run: |
          #       bdep init -C ../vermillon-gcc cc config.c=gcc config.cxx=g++
          #       #b -v
          #       #b -vn clean update |& compiledb 
          #       #cat compile_commands.json

      - name: Get hdoc 
        run: |
          git clone https://github.com/hdoc/hdoc
          cd hdoc
          sudo meson build && sudo ninja -C build
          cd ../
          sudo hdoc/build/hdoc 

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hdoc-output
